#
# ~/.bashrc
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

alias ls='ls --color=auto'
alias ls='ls --color=auto'
alias ll="ls -lA --group-directories-first"
alias ll="exa -la --group-directories-first"
alias set_monitor="xrandr --output HDMI-1 --auto --left-of eDP-1"
alias set_monitor_off="xrandr --output HDMI-1 --off"
alias set_monitor_rate="xrandr --output HDMI-1 --mode 1920x1080 -r 75"
alias fud="source fud"
alias mdprev="markdown-reader"
alias ..="cd ../"
alias ...="cd ../../"
alias pdf_make="pandoc -f markdown-implicit_figures -t pdf -V geometry:margin=1in -o report.pdf"



alias reset-ipsec="sudo ipsec down ni-vpn && sleep 1 && sudo ipsec up ni-vpn"



#language correction to locales
export LC_ALL=C

#history in cache directory
HISTSIZE=10000
SAVEHIST=10000
HISTFILE=~/.cache/bash/history

# path update for scripts and go
export PATH="$PATH:$HOME/go/bin"
export PATH="$PATH:$HOME/.local/bin"
export PATH="$PATH:$HOME/.cargo/bin"
export EDITOR=nvim

alias du=dust
alias grep=rg

alias nv=nvim
alias matlab='/home/sorin/.local/matlab_tmp/bin/matlab'
alias impss="import png:- | xclip -selection c -t image/png"
alias t=tmux
alias steam="DRI_PRIME=1 steam"
alias music_server="minidlnad"


alias wake_tank="wol -v 6c:62:6d:d8:c4:b5 --ipaddr=192.168.100.108"
alias close_tank="ssh -t tank 'sudo shutdown -h now'"
alias yt-dlp="bash ~/clones/yt-dlp/yt-dlp.sh"

alias ddd="~/Downloads/Discord/Discord & disown"
alias faculta="cd faculta/master/anu2/sem1"

alias kill_frog="ssh -t frog 'sudo shutdown -h now'"

# source /home/sorin/.config/broot/launcher/bash/br
export BROWSER=firefox

PS1='[\u@\h \W]\$ '
export STARSHIP_CONFIG="/home/sorin/.config/starship/starship.toml"
eval "$(starship init bash)"

# Avoid duplicates
HISTCONTROL=ignoredups:erasedups
# When the shell exits, append to the history file instead of overwriting it
shopt -s histappend

# After each command, append to the history file and reread it
PROMPT_COMMAND="${PROMPT_COMMAND:+$PROMPT_COMMAND$'\n'}history -a; history -c; history -r"
